#!/bin/sh
curl localhost:8080/products
curl localhost:8080/products/1
curl localhost:8080/products/10
curl -X POST localhost:8080/products
curl -X POST -d 'id_category=erro' localhost:8080/products
curl -X POST -d 'id_category=1' localhost:8080/products
curl -X POST -d 'id_category=1&name=A' localhost:8080/products
curl -X POST -d 'id_category=1&name=Meu+nome+de+produto+muito+grande' localhost:8080/products
curl -X POST -d 'id_category=1&name=Meu+produto' localhost:8080/products
curl -X POST -d 'id_category=1&name=Meu+produto&sku=TESTE' localhost:8080/products
curl -X POST -d 'id_category=1&name=Meu+produto&sku=TESTE00000' localhost:8080/products
curl -X POST -d 'id_category=1&name=Meu+produto&sku=TESTE00000&price=0' localhost:8080/products
curl -X POST -d 'id_category=1&name=Meu+produto&sku=TESTE00000&price=10' localhost:8080/products
curl -X POST -d 'products[0][id_category]=1&products[0][name]=Meu+produto+1&products[0][sku]=BULK000001&products[0][price]=10&products[1][id_category]=2&products[1][name]=Meu+produto+2&products[1][sku]=BULK000002&products[1][price]=20' localhost:8080/products
